holding <- read.table("household_power_consumption.txt", header = TRUE, skip = 66636, nrows = 2881, sep = ";")
colnames(holding) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
holding$Date <- strptime(holding$Date, "%d/%m/%Y")
png("plot1.png")
hist(holding$Global_active_power, col = "red", main = "Global Active Power",xlab = "Global Actrive Power(Kilowatts)")
dev.off()